#! /usr/local/bin/ruby
require 'socket'



class Actuator
  @@commands = ["start","stop"]


  # 等待请求
  def run
    server = TCPServer.open(2013)
    loop do
      Thread.start(server.accept) do |client|
        command = client.gets.rstrip
        param = client.gets.rstrip
        if(@@commands.include?(command))
          # client.puts("OK!")
          eval("#{command}('#{param}')")
        end
        client.close
      end
    end
  end

  def start(name)
    file = "assets/music/#{name}"
    if File.exist?(file)
      `mplayer -slave -input file=mplayer_fifofile #{file} > /dev/null`
    else
      puts "file #{name} not exists"
    end
  end

  def index(param)

  end

  def stop(param)
    output = open("mplayer_fifofile", "w")
    output.puts "quit"
    output.flush
  end

end

actuator = Actuator.new

actuator.run